### ISSUE TITLE
Quill v2 support

### ISSUE THREAD

**Issue by boris-petrov** [juyeong1260/quill-auto-detect-url#2]
@juyeong1260 thanks for the great package! I've been using it in Quill v1 and loving it. :) Do you plan on supporting Quill v2 which has been available for a few months now? Thanks!

**Comment by juyeong1260** [comment]
@boris-petrov 
First of all, thank you for using this package! I’m not currently using Quill myself, so I haven’t planned to support v2 yet. However, I agree that supporting it is essential as part of maintaining an open-source project. Would it be okay if I take a look at the v2 changelog and get back to you with an estimated timeframe for support?

**Comment by boris-petrov** [comment]
@juyeong1260 of course, take your time, there is no hurry. :) Actually the plugin seems to work just fine with Quill 2 as far as I have tested. One thing you could do is update the version of `quill-delta` to match what Quill 2 uses - 5.1.0 - and release that as a minor version. After that you can try more scenarios to see if the plugin is really fully compatible with Quill 2. [Here](https://quilljs.com/docs/upgrading-to-2-0) is Quill 2's upgrade guide.

Thanks again for the plugin!

**Comment by juyeong1260** [comment]
@boris-petrov 
In this [PR](https://github.com/juyeong1260/quill-auto-detect-url/pull/3), I've updated the project to support Quill Version 2. While I’ve tested it locally, I haven't been able to test it across various environments, so I've released it as an [alpha version](https://www.npmjs.com/package/quill-auto-detect-url/v/1.0.0-alpha.0). Could you please check if it works well in your setup?

**Comment by boris-petrov** [comment]
@juyeong1260 thanks for the quick update! You've made a [typo](https://github.com/juyeong1260/quill-auto-detect-url/pull/3/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R53) though so I can't install alpha.0 - please rename `quill-detla` to `quill-delta` and release alpha.1 and I'll test it. :)

**Comment by juyeong1260** [comment]
@boris-petrov Sorry.. I’ve made the changes in version 1.0.0-alpha.1. Please check and let me know if everything looks good. Thank you!

**Comment by boris-petrov** [comment]
@juyeong1260 thanks! All seems good now, I've tested (quickly) and it seems to work great. Thanks again for the support!

**Comment by juyeong1260** [comment]
@boris-petrov Thank you for your report and support! Please leave an issue if you encounter any other problems while using it.
